// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipservice.proto

/*
Package pipservice is a generated protocol buffer package.

It is generated from these files:
	pipservice.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	Request
	Response
*/
package pipservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_OK               Response_Status = 0
	Response_NOTFOUND         Response_Status = 1
	Response_INSUFFICIENTDATA Response_Status = 2
	Response_NOTAPPLICABLE    Response_Status = 3
	Response_GENERALERROR     Response_Status = 4
	Response_SERVICEERROR     Response_Status = 5
	Response_FATALERROR       Response_Status = 6
)

var Response_Status_name = map[int32]string{
	0: "OK",
	1: "NOTFOUND",
	2: "INSUFFICIENTDATA",
	3: "NOTAPPLICABLE",
	4: "GENERALERROR",
	5: "SERVICEERROR",
	6: "FATALERROR",
}
var Response_Status_value = map[string]int32{
	"OK":               0,
	"NOTFOUND":         1,
	"INSUFFICIENTDATA": 2,
	"NOTAPPLICABLE":    3,
	"GENERALERROR":     4,
	"SERVICEERROR":     5,
	"FATALERROR":       6,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Request struct {
	QueryURL string `protobuf:"bytes,1,opt,name=queryURL" json:"queryURL,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetQueryURL() string {
	if m != nil {
		return m.QueryURL
	}
	return ""
}

// use a a string for easy testing
type Response struct {
	Status     Response_Status `protobuf:"varint,1,opt,name=status,enum=pipservice.Response_Status" json:"status,omitempty"`
	Categories string          `protobuf:"bytes,2,opt,name=categories" json:"categories,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_OK
}

func (m *Response) GetCategories() string {
	if m != nil {
		return m.Categories
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pipservice.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "pipservice.HelloReply")
	proto.RegisterType((*Request)(nil), "pipservice.Request")
	proto.RegisterType((*Response)(nil), "pipservice.Response")
	proto.RegisterEnum("pipservice.Response_Status", Response_Status_name, Response_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PIP service

type PIPClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Sends a query
	GetCategories(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pIPClient struct {
	cc *grpc.ClientConn
}

func NewPIPClient(cc *grpc.ClientConn) PIPClient {
	return &pIPClient{cc}
}

func (c *pIPClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/pipservice.PIP/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pIPClient) GetCategories(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pipservice.PIP/GetCategories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PIP service

type PIPServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Sends a query
	GetCategories(context.Context, *Request) (*Response, error)
}

func RegisterPIPServer(s *grpc.Server, srv PIPServer) {
	s.RegisterService(&_PIP_serviceDesc, srv)
}

func _PIP_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIPServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipservice.PIP/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIPServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PIP_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIPServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipservice.PIP/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIPServer).GetCategories(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PIP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pipservice.PIP",
	HandlerType: (*PIPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _PIP_SayHello_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _PIP_GetCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pipservice.proto",
}

func init() { proto.RegisterFile("pipservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x86, 0x8d, 0xda, 0x98, 0x0e, 0x2a, 0xdb, 0xa9, 0x94, 0x60, 0xa1, 0x94, 0x85, 0x96, 0x9e,
	0x3c, 0xe8, 0xb5, 0x14, 0xd2, 0xb8, 0xb1, 0xa1, 0x21, 0x09, 0x9b, 0xd8, 0x7b, 0x2a, 0x8b, 0x08,
	0xd1, 0xc4, 0x6c, 0x2c, 0x84, 0x1e, 0xfb, 0x9a, 0x7d, 0x98, 0xd2, 0x68, 0x6c, 0x0a, 0xde, 0x76,
	0xfe, 0xfd, 0x66, 0xd8, 0xf9, 0x16, 0x48, 0xba, 0x4a, 0xa5, 0xc8, 0x3e, 0x56, 0x0b, 0x31, 0x4a,
	0xb3, 0x24, 0x4f, 0x10, 0xfe, 0x12, 0x4a, 0xa1, 0xfb, 0x22, 0xe2, 0x38, 0xe1, 0x62, 0xbb, 0x13,
	0x32, 0x47, 0x84, 0xf6, 0x26, 0x5a, 0x0b, 0x5d, 0xb9, 0x55, 0x1e, 0xce, 0x79, 0x79, 0xa6, 0xf7,
	0x00, 0x07, 0x26, 0x8d, 0x0b, 0xd4, 0xa1, 0xb3, 0x16, 0x52, 0x46, 0xcb, 0x0a, 0xaa, 0x4a, 0x7a,
	0x07, 0x9d, 0x6a, 0xcc, 0x10, 0xb4, 0xed, 0x4e, 0x64, 0xc5, 0x9c, 0x3b, 0x07, 0xea, 0x58, 0xd3,
	0x6f, 0x05, 0x34, 0x2e, 0x64, 0x9a, 0x6c, 0xa4, 0xc0, 0x09, 0xa8, 0x32, 0x8f, 0xf2, 0x9d, 0x2c,
	0xb1, 0xfe, 0xf8, 0x7a, 0x54, 0x7b, 0x6e, 0x45, 0x8d, 0x82, 0x12, 0xe1, 0x07, 0x14, 0x6f, 0x00,
	0x16, 0x51, 0x2e, 0x96, 0x49, 0xb6, 0x12, 0x52, 0x6f, 0x96, 0xf3, 0x6b, 0x09, 0xfd, 0x04, 0x75,
	0xdf, 0x81, 0x2a, 0x34, 0xbd, 0x57, 0xd2, 0xc0, 0x2e, 0x68, 0xae, 0x17, 0x5a, 0xde, 0xdc, 0x9d,
	0x12, 0x05, 0x07, 0x40, 0x6c, 0x37, 0x98, 0x5b, 0x96, 0x6d, 0xda, 0xcc, 0x0d, 0xa7, 0x46, 0x68,
	0x90, 0x26, 0x5e, 0x40, 0xcf, 0xf5, 0x42, 0xc3, 0xf7, 0x1d, 0xdb, 0x34, 0x9e, 0x1d, 0x46, 0x5a,
	0x48, 0xa0, 0x3b, 0x63, 0x2e, 0xe3, 0x86, 0xc3, 0x38, 0xf7, 0x38, 0x69, 0xff, 0x26, 0x01, 0xe3,
	0x6f, 0xb6, 0xc9, 0xf6, 0xc9, 0x19, 0xf6, 0x01, 0x2c, 0x23, 0xac, 0x08, 0x75, 0xfc, 0xa5, 0x40,
	0xcb, 0xb7, 0x7d, 0x7c, 0x02, 0x2d, 0x88, 0x8a, 0x52, 0x1c, 0xea, 0xf5, 0xad, 0xea, 0xbe, 0x87,
	0x57, 0x27, 0x6e, 0xd2, 0xb8, 0xa0, 0x0d, 0x7c, 0x84, 0xde, 0x4c, 0xe4, 0xe6, 0x71, 0x2b, 0xbc,
	0xfc, 0xaf, 0x66, 0xdf, 0x3f, 0x38, 0xe5, 0x8b, 0x36, 0xde, 0xd5, 0xf2, 0xab, 0x27, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0x7d, 0x5d, 0xc1, 0xfe, 0x01, 0x00, 0x00,
}
